version: 2.1

executors:
  gradle:
    docker:
      - image: circleci/openjdk:11-jdk
    working_directory: ~/main

jobs:
  build:
    executor: gradle
    steps:
      - checkout

      - run:
          name: Download and cache dependencies
          command: ./gradlew build --no-daemon

      - run:
          name: Build JAR
          command: ./gradlew build --no-daemon

      - run:
          name: List all files in build directory
          command: find build

      - store_artifacts:
          path: build/libs/java-hello-world.jar
          destination: java-hello-world.jar

workflows:
  version: 2
  build_jar:
    jobs:
      - build
