version: 2.1

executors:
  maven:
    docker:
      - image: circleci/openjdk:11-jdk
    working_directory: ~/main

jobs:
  build:
    executor: maven
    steps:
      - checkout

      - run:
          name: Download and cache dependencies
          command: mvn dependency:go-offline

      - run:
          name: Build WAR
          command: mvn clean package

      - run:
          name: List target directory contents
          command: ls -la target

      - store_artifacts:
          path: target/*.war
          destination: war-file

      - run:
          name: Creating Dummy Artifacts
          working_directory: /tmp
          command: |
            echo "my artifact file" > /tmp/artifact-1;
            mkdir /tmp/artifacts;
            echo "my artifact files in a dir" > /tmp/artifacts/artifact-2;

      - store_artifacts:
          path: /tmp/artifact-1
          destination: artifact-file

      - store_artifacts:
          path: /tmp/artifacts

workflows:
  version: 2
  build_war:
    jobs:
      - build
