version: 2.1

executors:
  maven:
    docker:
      - image: circleci/openjdk:11-jdk
    working_directory: ~/main

jobs:
  build:
    executor: maven
    steps:
      - checkout

      - run:
          name: Download and cache dependencies
          command: mvn dependency:go-offline

      - run:
          name: Build WAR
          command: mvn clean package

      - run:
          name: Rename WAR with Build Number
          command: |
            if [ -f target/java-hello-world.war ]; then
              mv target/java-hello-world.war target/${CIRCLE_BUILD_NUM}.war;
              echo "WAR file renamed to ${CIRCLE_BUILD_NUM}.war";
            else
              echo "WAR file not found!";
              exit 1;
            fi

      - run:
          name: List all files in target directory after renaming
          command: find target

      - run:
          name: Print artifact path
          command: echo "Artifact path: target/${CIRCLE_BUILD_NUM}.war"

      - store_artifacts:
          path: target/${CIRCLE_BUILD_NUM}.war
          destination: java-hello-world/${CIRCLE_BUILD_NUM}.war

workflows:
  version: 2
  build_war:
    jobs:
      - build
