version: 2.1

executors:
  gradle-executor:
    docker:
      - image: circleci/openjdk:11-jdk
    working_directory: ~/main

jobs:
  build:
    executor: gradle-executor
    steps:
      - checkout

      - run:
          name: Download and cache dependencies
          command: ./gradlew build --no-daemon

      - run:
          name: Build WAR
          command: ./gradlew clean build

      - run:
          name: List all files in build/libs directory
          command: find build/libs

      - store_artifacts:
          path: build/libs/*.war
          destination: gradle-build.war

workflows:
  version: 2
  build_war:
    jobs:
      - build
