version: 2.1

executors:
  maven:
    docker:
      - image: circleci/openjdk:11-jdk
    working_directory: ~/main

jobs:
  build:
    executor: maven
    steps:
      - checkout

      - run:
          name: Download and cache dependencies
          command: mvn dependency:go-offline

      - run:
          name: Build WAR
          command: mvn clean package

      - run:
          name: List all files in target directory
          command: find target

      - store_artifacts:
          path: target/java-hello-world/${CIRCLE_BUILD_NUM}.war
          destination: java-hello-world/${CIRCLE_BUILD_NUM}.war

workflows:
  version: 2
  build_war:
    jobs:
      - build
